from .multihash import Multihash

class CID:
    def __init__(self, version: int, codec: int, hash: Multihash) -> None: ...
    @staticmethod
    def decode(string: str) -> CID: ...
    @staticmethod
    def from_bytes(data: bytes) -> CID: ...
    @property
    def version(self) -> int: ...
    @property
    def codec(self) -> int: ...
    @property
    def hash(self) -> Multihash: ...
    def to_bytes(self) -> bytes: ...
    def encode(self, base: str | None = None) -> str: ...
    def to_v1(self) -> CID: ...
