def encode(base: str, data: bytes) -> str: ...
def decode(string: str) -> tuple[str, bytes]: ...
def bases() -> list[str]: ...

# Every encoding as an UPPERCASE constant holding its canonical name,
# e.g. BASE58BTC == "base58btc".
def __getattr__(constant: str) -> str: ...
