# Generated by build.rs from data/multibase-table.csv. Do not edit by hand.
from typing import Final

def encode(base: str, data: bytes) -> str: ...
def decode(string: str) -> tuple[str, bytes]: ...
def bases() -> list[str]: ...
def entries() -> list[tuple[str, str, str]]: ...

BASE2: Final = "base2"
BASE8: Final = "base8"
BASE10: Final = "base10"
BASE16: Final = "base16"
BASE16UPPER: Final = "base16upper"
BASE32HEX: Final = "base32hex"
BASE32HEXUPPER: Final = "base32hexupper"
BASE32HEXPAD: Final = "base32hexpad"
BASE32HEXPADUPPER: Final = "base32hexpadupper"
BASE32: Final = "base32"
BASE32UPPER: Final = "base32upper"
BASE32PAD: Final = "base32pad"
BASE32PADUPPER: Final = "base32padupper"
BASE32Z: Final = "base32z"
BASE36: Final = "base36"
BASE36UPPER: Final = "base36upper"
BASE45: Final = "base45"
BASE58BTC: Final = "base58btc"
BASE58FLICKR: Final = "base58flickr"
BASE64: Final = "base64"
BASE64PAD: Final = "base64pad"
BASE64URL: Final = "base64url"
BASE64URLPAD: Final = "base64urlpad"
PROQUINT: Final = "proquint"
BASE256EMOJI: Final = "base256emoji"
