def code(name: str) -> int: ...
def name(code: int) -> str: ...
def tag(codec: int | str) -> str: ...
def entries() -> list[tuple[str, str, int, str]]: ...

# Every registry entry is exposed as an UPPER_SNAKE_CASE integer constant,
# e.g. DAG_PB, RAW, SHA2_256, LIBP2P_KEY.
def __getattr__(constant: str) -> int: ...
