class Multihash:
    @staticmethod
    def wrap(code: int, digest: bytes) -> Multihash: ...
    @staticmethod
    def from_bytes(data: bytes) -> Multihash: ...
    @property
    def code(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def size(self) -> int: ...
    @property
    def digest(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...

def digest(algorithm: str | int, data: bytes) -> Multihash: ...
def codes() -> dict[str, int]: ...
def identity(data: bytes) -> Multihash: ...
def sha1(data: bytes) -> Multihash: ...
def sha2_256(data: bytes) -> Multihash: ...
def sha2_512(data: bytes) -> Multihash: ...
def sha3_224(data: bytes) -> Multihash: ...
def sha3_256(data: bytes) -> Multihash: ...
def sha3_384(data: bytes) -> Multihash: ...
def sha3_512(data: bytes) -> Multihash: ...
def keccak_224(data: bytes) -> Multihash: ...
def keccak_256(data: bytes) -> Multihash: ...
def keccak_384(data: bytes) -> Multihash: ...
def keccak_512(data: bytes) -> Multihash: ...
def blake3(data: bytes) -> Multihash: ...
def blake2b_256(data: bytes) -> Multihash: ...
def blake2b_512(data: bytes) -> Multihash: ...
def blake2s_128(data: bytes) -> Multihash: ...
def blake2s_256(data: bytes) -> Multihash: ...
def ripemd_160(data: bytes) -> Multihash: ...
def ripemd_256(data: bytes) -> Multihash: ...
def ripemd_320(data: bytes) -> Multihash: ...
