from collections.abc import Iterator

class Multiaddr:
    def __init__(self, addr: str) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> Multiaddr: ...
    def to_bytes(self) -> bytes: ...
    def protocols(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str | None]]: ...
    def encapsulate(self, other: Multiaddr | str) -> Multiaddr: ...
    def decapsulate(self, other: Multiaddr | str) -> Multiaddr: ...
    def __iter__(self) -> Iterator[tuple[str, str | None]]: ...
    def __len__(self) -> int: ...
