# Generated by build.rs from data/multibase-table.csv. Do not edit by hand.
from enum import Enum

def encode(base: str, data: bytes) -> str: ...
def decode(string: str) -> tuple[str, bytes]: ...
def bases() -> list[str]: ...
def entries() -> list[tuple[str, str, str, str]]: ...

class Multibase(str, Enum):
    """A multibase registry entry, e.g. ``Multibase.BASE58BTC``.

    Behaves as its canonical name string (``Multibase.BASE58BTC == "base58btc"``)
    and carries the registry's prefix, description, and status.
    """

    prefix: str
    description: str
    status: str

    def encode(self, data: bytes) -> str: ...

    BASE2 = "base2"
    BASE8 = "base8"
    BASE10 = "base10"
    BASE16 = "base16"
    BASE16UPPER = "base16upper"
    BASE32HEX = "base32hex"
    BASE32HEXUPPER = "base32hexupper"
    BASE32HEXPAD = "base32hexpad"
    BASE32HEXPADUPPER = "base32hexpadupper"
    BASE32 = "base32"
    BASE32UPPER = "base32upper"
    BASE32PAD = "base32pad"
    BASE32PADUPPER = "base32padupper"
    BASE32Z = "base32z"
    BASE36 = "base36"
    BASE36UPPER = "base36upper"
    BASE45 = "base45"
    BASE58BTC = "base58btc"
    BASE58FLICKR = "base58flickr"
    BASE64 = "base64"
    BASE64PAD = "base64pad"
    BASE64URL = "base64url"
    BASE64URLPAD = "base64urlpad"
    PROQUINT = "proquint"
    BASE256EMOJI = "base256emoji"
